export const commonIcon = {
  add: "ic:round-add",
  edit: "ic:round-edit",
  delete: "ic:round-delete",
  filter: "ic:round-filter-list",
  sort: "ic:round-sort",
  close: "ic:round-close",
  check: "lucide:check",
  save: "ic:round-save",
  cancel: "ic:round-cancel",
  checkCircle: "ic:round-check-circle",
  calendar: "lucide:calendar",
  chevronDown: "lucide:chevron-down",
  chevronUp: "lucide:chevron-up",
  chevronLeft: "lucide:chevron-left",
  chevronRight: "lucide:chevron-right",
  loader: "lucide:loader-circle",
  searchIcon: "lucide:search",
  x: "lucide:x",
  circle: "lucide:circle",
  sparkles: "lucide:sparkles",
  circleAlert: "lucide:circle-alert",
};
